#!/usr/bin/env bash

# Some tools will straight up ignore ~/.bash_profile and only look at
# ~/.bashrc, so just put everything in there.

if [ -f ~/.bashrc ]; then
  source ~/.bashrc
fi
. "$HOME/.cargo/env"

# >>> juliaup initialize >>>

# !! Contents within this block are managed by juliaup !!

case ":$PATH:" in
    *:/Users/qimer/.juliaup/bin:*)
        ;;

    *)
        export PATH=/Users/qimer/.juliaup/bin${PATH:+:${PATH}}
        ;;
esac

# <<< juliaup initialize <<<
