#!/usr/bin/env bash

# Some tools will straight up ignore ~/.bash_profile and only look at
# ~/.bashrc, so just put everything in there.

if [ -f ~/.bashrc ]; then
  source ~/.bashrc
fi

# >>> juliaup initialize >>>

# !! Contents within this block are managed by juliaup !!

case ":$PATH:" in
    *:/Users/qimer/.juliaup/bin:*)
        ;;

    *)
        export PATH=/Users/qimer/.juliaup/bin${PATH:+:${PATH}}
        ;;
esac

# <<< juliaup initialize <<<

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

export PATH="$HOME/.elan/bin:$PATH"
. "$HOME/.cargo/env"
