#! /bin/bash

export BASH_SILENCE_DEPRECATION_WARNING=1

# DEBUGGING
# echo '.bash_profile'

# PROMPT
# Color the hostname
# Light Blue
export HOST_COLOR="\[\033[1;36m\]"
# Blue
export HOST_COLOR="\[\033[1;34m\]"
# Red
export HOST_COLOR="\[\033[1;31m\]"
# Light Purple
export HOST_COLOR="\[\033[1;35m\]"
# Green
export HOST_COLOR="\[\033[1;32m\]"
# Yellow
export WD_COLOR="\[\033[1;33m\]"
export DATE_COLOR="\[\033[1;37m\]"

export CMD_COLOR="\[\033[00m\]"
export VIM_COLOR="\[\033[00m\]"
export VIM_COLOR="\[\033[1;35m\]"

# Color the colon red if root
export COLON_COLOR='0m'
if [ ${UID} -eq 0 ]; then
    export COLON_COLOR='1;31m'
fi
PS1="$DATE_COLOR<\D{%H:%M:%S}>$VIM_COLOR${VIM##*/}$HOST_COLOR$(scutil --get LocalHostName)\[\033[00m\]\[\e[$COLON_COLOR\]:$WD_COLOR[\w]\$$CMD_COLOR "

# FUNCTIONS
function mkcd() {
    mkdir "$@"
    cd "${@: -1}"
}

function cls() {
    printf "\033c"
}

function path() {
    echo -e ${PATH//:/\\n}
}

function now() {
    date +"%T"
}

function nowtime() {
    now
}

function nowdate() {
    date +"%d-%m-%Y"
}

function ports() {
    netstat -tulanp
}

function csvtable() {
    column -s, -t
}

function work() {
    tmux new -t "${1}"
}

UNAME_S=$(uname -s)
if [[ "${UNAME_S}" == "Darwin" ]]; then
    function manpdf() {
        man -t $1 | open -f -a /Applications/Preview.app
    }
fi

# ALIASES
alias ls="ls -G"
alias bc="bc -l"
alias grep="grep --color=auto"
alias egrep="egrep --color=auto"
alias fgrep="fgrep --color=auto"
alias tree="tree -C"

if [ -f ~/.bashrc ]; then
    source ~/.bashrc
fi

### Python ###

PATH="/System/Library/Frameworks:/AppleInternal/Library/Frameworks:$PATH"
#PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
# Setting PATH for Python 3.6
# The original version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.6/bin:${PATH}"
export PATH
export TERM=xterm-256color
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# Setting PATH for Python 3.7
# The original version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.7/bin:${PATH}"
export PATH

### Golang ###
export GOPATH="$HOME/go"
export PATH="$PATH:$GOPATH/bin"


### Ruby ###
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
export PATH=/usr/local/opt/ruby/bin:$PATH
source $(brew --prefix)/opt/chruby/share/chruby/chruby.sh
source $(brew --prefix)/opt/chruby/share/chruby/auto.sh

# Needs to go after the above, which I think makes the Homebrew Ruby the one used for this command
# Pilfered from: https://stackoverflow.com/a/36485733
export PATH="$PATH:`ruby -e 'puts Gem.user_dir'`/bin"

# Ruby/Jekyll Stuffs
# https://jekyllrb.com/docs/installation/macos/
# export GEM_HOME=$HOME/.gem
# export PATH=$PATH:$HOME/.gem/bin
# export PATH=$PATH:$HOME/.gem/ruby/2.5.0/bin
