require("rectangleboy.close")
require("rectangleboy.set")
require("rectangleboy.remap")
require("rectangleboy.number")
require("rectangleboy.search")
require("rectangleboy.shell")
require("rectangleboy.autocomplete")
require("rectangleboy.lsp")
