;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[colors]
;background = #BCC3C3
;background-alt = #002B36
;foreground = #002B36
;foreground-alt = #BCC3C3
;primary = #ffb52a
;secondary = #e60053
;alert = #FF0000
; AlienBlood attempt
background = #1D4125
background-alt = #112616
foreground = #2FD0F4
foreground-alt = #FFFFFF
primary = #1D4125
secondary = #e60053
alert = #FF0000

[internal/tray]
position = right
padding = 0
detached = false
maxsize = 14
scale = 1.0
background = ${colors.background-alt}
foreground = ${colors.foreground-alt}
offset-x = 0
offset-y = 0

[bar/example]
monitor = ${env:MONITOR:}
width = 100%
height = 25
radius = 0.0
fixed-center = true
top = yes
bottom = no
override-false = false

foreground = ${colors.foreground-alt}
background = ${colors.background-alt}

; Under-/overline pixel size and argb color
; Individual values can be defined using:
;   {overline,underline}-size
;   {overline,underline}-color
line-size = 1
line-color = #dfdfdf

border-top-size = 0
border-bottom-size = 0
border-left-size = 0
border-right-size = 0

padding-left = 0
padding-right = 0

module-margin-left = 0
module-margin-right = 0

font-0 = fixed:pixelsize=10;1
font-2 = "Wuncon Siji:pixelsize=10;3"
font-1 = Weather Icons:style=Regular:size=10;2
font-3 = UbuntuMono Nerd Font Mono:pixelsize=20;1
font-4 = UbuntuMono Nerd Font Mono:pixelsize=10;1


modules-left = i3
modules-right = weather sep1 linux-ver sep1 updates sep2 pulseaudio sep2 date sep2

wm-restack = i3

scroll-up = #i3.next
scroll-down = #i3.prev

cursor-click = pointer


[module/sep1]
type = custom/text
format = " | "
content-foreground = #93A1A1
content-background = ${colors.background-alt}

[module/sep2]
type = custom/text
format = " |"
content-foreground = #93A1A1
content-background = ${colors.background-alt}

[module/i3]
type = internal/i3
format = <label-state> <label-mode>
index-sort = true
wrapping-scroll = false
strip-wsnumbers = false
enable-click = false
enable-scroll = false

label-mode = %mode%
label-mode-padding = 1
label-mode-foreground = ${colors.foreground-alt}
label-mode-background = ${colors.background-alt}

; focused = Active workspace on focused monitor
label-focused = %index%
label-focused-foreground = ${colors.foreground}
label-focused-background = ${colors.background}
label-focused-underline = ${colors.foreground-alt}
label-focused-padding = 1

; unfocused = Inactive workspace on any monitor
label-unfocused = %index%
label-unfocused-padding = ${self.label-focused-padding}
label-unfocused-foreground = ${colors.foreground-alt}
label-unfocused-background = ${colors.background-alt}

; visible = Active workspace on unfocused monitor
label-visible = %index%
label-visible-foreground = ${self.label-focused-background}
label-visible-background = ${self.label-focused-foreground}
label-visible-underline = ${self.label-focused-underline}
label-visible-padding = ${self.label-focused-padding}

; urgent = Workspace with urgency hint set
label-urgent = %index%
label-urgent-foreground = ${colors.foreground}
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

; Separator in between workspaces
label-separator =
label-separator-padding = 0
label-separator-foreground = #fff

[module/info-hackspeed]
type = custom/script
exec = ~/.config/polybar/scripts/info-hackspeed.sh
tail = true

[module/weather]
type = custom/script
exec = ~/.config/polybar/scripts/weather-openmap.sh
interval = 600

[module/linux-ver]
type = custom/script
exec = uname -r
interval = 600

[module/updates]
type = custom/script
exec = ~/.config/polybar/scripts/arch_updates.sh
interval = 60
label = %output%

[module/date]
type = internal/date
interval = 0.97
time = "%a %Y-%m-%dT%H:%M:%S%Z"

format-prefix = " "
format-prefix-foreground = ${colors.foreground-alt}
format-prefix-background = ${colors.background-alt}

label = %time%
label-foreground = ${colors.foreground-alt}
label-background = ${colors.background-alt}

[module/alsa]
type = internal/alsa

; Soundcard to be used
; Usually in the format hw:# where # is the card number
; You can find the different card numbers in `/proc/asound/cards`
master-soundcard = default
speaker-soundcard = default
headphone-soundcard = default

; Name of the master, speaker and headphone mixers
; Use the following command to list available mixer controls:
; $ amixer scontrols | sed -nr "s/.*'([[:alnum:]]+)'.*/\1/p"
; If master, speaker or headphone-soundcard isn't the default,
; use `amixer -c # scontrols` instead where # is the number
; of the master, speaker or headphone soundcard respectively
;
; Default: Master
master-mixer = Master

format-volume = "<label-volume><bar-volume>"
label-volume = " "
label-volume-foreground = ${colors.foreground-alt}
label-volume-background = ${colors.background-alt}

format-muted-prefix = " "
format-muted-foreground = ${colors.foreground-alt}
format-muted-background = ${colors.background-alt}
label-muted = MUTED

bar-volume-width = 10
bar-volume-foreground-0 = ${colors.foreground-alt}
bar-volume-foreground-1 = ${colors.foreground-alt}
bar-volume-foreground-2 = ${colors.foreground-alt}
bar-volume-foreground-3 = ${colors.foreground-alt}
bar-volume-foreground-4 = ${colors.foreground-alt}
bar-volume-foreground-5 = ${colors.foreground-alt}
bar-volume-foreground-6 = ${colors.foreground-alt}
bar-volume-gradient = false
bar-volume-indicator = |
bar-volume-indicator-font = 1
bar-volume-indicator-foreground = ${colors.foreground-alt}
bar-volume-indicator-background = ${colors.background-alt}
bar-volume-fill = -
bar-volume-fill-font = 1
bar-volume-fill-foreground = ${colors.foreground-alt}
bar-volume-fill-background = ${colors.background-alt}
bar-volume-empty = -
bar-volume-empty-font = 1
bar-volume-empty-foreground = ${colors.foreground-alt}
bar-volume-empty-background = ${colors.background-alt}

[module/pulseaudio]
type = internal/pulseaudio

format-volume-underline = #00e200
format-volume-background = ${colors.background-mod}
format-volume-prefix = " "
format-volume = <label-volume> <bar-volume>
label-volume = %percentage%%
label-volume-foreground = ${root.foreground}

format-muted-underline = #006200
format-muted-background = ${colors.background-mod}
format-muted-prefix = " "
format-muted-foreground = ${colors.foreground-alt}
label-muted = muted

bar-volume-width = 10
bar-volume-foreground-0 = #55aa55
bar-volume-foreground-1 = #55aa55
bar-volume-foreground-2 = #55aa55
bar-volume-foreground-3 = #55aa55
bar-volume-foreground-4 = #55aa55
bar-volume-foreground-5 = #f5a70a
bar-volume-foreground-6 = #ff5555
bar-volume-gradient = true
bar-volume-indicator = /
bar-volume-indicator-font = 2
bar-volume-fill = /
bar-volume-fill-font = 2
bar-volume-empty = /
bar-volume-empty-font = 2
bar-volume-empty-foreground = ${colors.foreground-alt}

interval = 2

[settings]
screenchange-reload = true
compositing-background = over
compositing-foreground = over
compositing-overline = over
compositing-border = over

[global/wm]
margin-top = 5
margin-bottom = 5
