#! /bin/bash

# DEBUGGING
echo '.bash_profile'

# PROMPT

# Color the hostname
# Light Blue
export HOST_COLOR="\[\033[1;36m\]"
# Blue
export HOST_COLOR="\[\033[1;34m\]"
# Orange
export HOST_COLOR="\[\033[1;31m\]"

# Color the colon red if root
COLON_COLOR='0m'
if [ ${UID} -eq 0 ]; then
    COLON_COLOR='1;31m'
fi
PS1=`echo -ne "$HOST_COLOR\h\[\033[00m\]\[\e[$COLON_COLOR\]:\[\033[01;32m\][\w]\[\033[00m\]\\[\033[01;33m\]\$\[\033[00m\] "`

# FUNCTIONS
function mkcd() {
    mkdir "$@"
    cd "${@: -1}"
}

function cls() {
    printf "\033c"
}

function path() {
    echo -e ${PATH//:/\\n}
}

function now() {
    date +"%T"
}

function nowtime() {
    now
}

function nowdate() {
    date +"%d-%m-%Y"
}

function ports() {
    netstat -tulanp
}

function csvtable() {
    column -s, -t
}

UNAME_S=$(uname -s)
if [[ "${UNAME_S}" == "Darwin" ]]; then
    function manpdf() {
        man -t $1 | open -f -a /Applications/Preview.app
    }
fi


# ALIASES
alias ls="ls -G"
alias bc="bc -l"
alias grep="grep --color=auto"
alias egrep="egrep --color=auto"
alias fgrep="fgrep --color=auto"
alias tree="tree -C"

if [ -f ~/.bashrc ]; then
    source ~/.bashrc
fi
