"====[ BEGIN ~/.vimrc ]====
" Preferred Location: ~/.vimrc
" Author: Jeff McGovern

"====[ Minimal .vimrc (Pilfered) ]====
" Minimal .vimrc pilfered (almost exactly) from:
" http://stackoverflow.com/questions/1840862/favorite-minimalistic-vimrc-configuration
setlocal backspace=2 " backspace in insert mode works like normal editor
syntax on            " syntax highlighting
filetype indent on   " activates indenting for files
setlocal autoindent  " auto indenting
setlocal number      " line numbers
colorscheme desert   " colorscheme desert
setlocal nobackup    " get rid of anoying ~file

"====[ Color Scheme ]====
colorscheme desert
" colorscheme slate
" colorscheme retrobox
" colorscheme delek  " horrendous with ctermbg=NONE
" colorscheme 3dglasses
" colorscheme Benokai
" colorscheme xoria256

highlight Normal guibg=NONE ctermbg=NONE
highlight nonText guibg=NONE ctermbg=NONE
highlight LineNr guibg=NONE ctermbg=NONE
highlight MatchParen cterm=bold ctermbg=none ctermfg=magenta


"====[ Mouse Support ]====
set mouse=a

"====[ Define Shell ]====
" Sources .bash_profile upon :sh
set shell=bash\ --login
" Makes tab complete work like bash
set wildmode=longest,list

"====[ Highlight Search ]====
func ToggleHighlight()
    if (&hlsearch == 1)
        set nohlsearch
    else
        set hlsearch
    endif
endfunc
nnoremap <C-H> :call ToggleHighlight()<cr>
set hlsearch

"====[ Ignoring Case ]====
setlocal ignorecase
setlocal smartcase

"====[ Turn Off Error Noises ]====

setlocal novisualbell " remove annoying visual beeps
setlocal noerrorbells " remove annoying audio beeps

"====[ Tabs to Spaces ]====

" DEFAULT: 4 space tabs
" expandtab: means TAB key will insert <sofftabstop> number of spaces
" set used because setlocal didn't work for vim -O (inserted tab)
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab

"====[ Tabs, trailing whitespace, and non-breaking spaces visible ]====

set listchars=tab:»»,trail:·,nbsp:~
set list

"====[ Ruler ]====

" Displays the row,col in the bottom right
set ruler

"====[ Relative Line Numbering ]====

" change to absolute line numbering
function! SetLineNumber()
    setlocal norelativenumber
    setlocal number
endfunc
" change to relative line numbering
function! SetRelativeLineNumber()
    setlocal relativenumber
    setlocal number
endfunc
" toggles relative/absolute line
function! ToggleLineNumStyle()
    if (&relativenumber == 1)
        call SetLineNumber()
    else
        call SetRelativeLineNumber()
    endif
endfunc
" ctrl + n calls toggle
nnoremap <C-n> :call ToggleLineNumStyle()<cr>
" DEFAULT: relative line numbering
set relativenumber
set number
" only relative when pane in focus
:autocmd WinLeave * call SetLineNumber()
:autocmd WinEnter * call SetRelativeLineNumber()
" switches to absolute when in insert
autocmd InsertEnter * call SetLineNumber()
autocmd InsertLeave * call SetRelativeLineNumber()

"====[ Case Insensitive Save and Quit Commands ]====

:command WQA wqa
:command WQa wqa
:command Wqa wqa
:command QA qa
:command Qa qa
:command WA wa
:command Wa wa
:command WQ wq
:command Wq wq
:command W w
:command Q q

"====[ BEGIN Vundle ]====
"##### PREREQUISITES
" git clone
" curl
"##### SETUP
" git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
"##### CONFIGURE
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" Fundamentals
Plugin 'ahw/vim-pbcopy' " 1) select in Visual Mode; 2) cy ==> clipboard
Plugin 'eapache/rainbow_parentheses.vim'
Plugin 'mbbill/undotree'

" Autocomplete
Plugin 'ervandew/supertab' " :help supertab

" Tim Pope
Plugin 'tpope/vim-fugitive' " git interaction
Plugin 'tpope/vim-repeat' " remaps . in a way that plugins can tap into it

" Markdown
Plugin 'jmcgover/markdown-preview.nvim', {'name': 'jmcgover-markdown-preview.nvim'} " fork of iamcco/markdown-preview.nvim
Plugin 'godlygeek/tabular'
Plugin 'preservim/vim-markdown'

" Just
" https://just.systems/man/en/vim-and-neovim.html
Plugin 'NoahTheDuke/vim-just'

" fzf
Plugin 'junegunn/fzf' " , { 'do': { -> fzf#install() } }
Plugin 'junegunn/fzf.vim'

" Airline needs Powerline-patched fonts, which are here:
"   https://github.com/powerline/fonts
" Notable Fonts:
"   - DejaVu Sans Mono for Powerline
"   - Droid Sans Mono for Powerline
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'powerline/powerline'

" Google Vim Plugin
Plugin 'google/vim-maktaba'
Plugin 'google/vim-glaive' " before use, run: call glaive#Install()
Plugin 'google/vim-codefmt'


" ALL PLUGINS MUST BE ADDED BEFORE THE FOLLOWING LINE
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line
"##### INSTALL

"====[ END Vundle ]====

"====[ eapache/rainbow_parentheses.vim ]====
let g:rbpt_colorpairs = [
   \ ['red',         'RoyalBlue3'],
   \ ['blue',        'DarkOrchid3'],
   \ ['brown',       'SeaGreen3'],
   \ ['gray',        'firebrick3'],
   \ ['green',       'RoyalBlue3'],
   \ ['magenta',     'SeaGreen3'],
   \ ['cyan',        'DarkOrchid3'],
   \ ['darkred',     'firebrick3'],
   \ ['brown',       'RoyalBlue3'],
   \ ['darkblue',    'DarkOrchid3'],
   \ ['gray',        'firebrick3'],
   \ ['darkgreen',   'RoyalBlue3'],
   \ ['darkmagenta', 'SeaGreen3'],
   \ ['darkcyan',    'DarkOrchid3'],
   \ ['red',         'firebrick3'],
   \ ]
" How deep to colour (repeating the colour list if necessary) before giving up; limited for performance reasons.
"let g:rbpt_max = 15
"let g:rbpt_loadcmd_toggle = 0
" Bold parenthese to make the colours stand out more
let g:bold_parentheses = 1 " Default on
" :RainbowParenthesesToggle       " Toggle it on/off
" :RainbowParenthesesLoadRound    " (), the default when toggling
" :RainbowParenthesesLoadSquare   " []
" :RainbowParenthesesLoadBraces   " {}
" :RainbowParenthesesLoadChevrons " <>
" To always use Rainbow Parenthesis:
au VimEnter * RainbowParenthesesToggle
au Syntax * RainbowParenthesesLoadRound
au Syntax * RainbowParenthesesLoadSquare
au Syntax * RainbowParenthesesLoadBraces

"====[ vim-airline/vim-airline ]====
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#left_sep = ' '
let g:airline#extensions#tabline#left_alt_sep = '|'
let g:airline_powerline_fonts = 1

"====[ vim-airline/vim-airline-themes ]====
":AirlineTheme simple
let g:airline_theme='base16'
let g:airline_theme='wombat'
let g:airline_theme='atomic'

"====[ mbbill/undotree ]====
nnoremap <F5> :UndotreeToggle<CR>
if has("persistent_undo")
   let target_path = expand('~/.vim-undodir')

    " create the directory and any parent directories
    " if the location does not exist.
    if !isdirectory(target_path)
        call mkdir(target_path, "p", 0700)
    endif

    let &undodir=target_path
    set undofile
endif

"====[ iamcco/markdown-preview.nvim ]====
"##### SETUP
":call mkdp#util#install()

" these filetypes will have MarkdownPreview... commands
let g:mkdp_filetypes = ['markdown']

" set to 1, nvim will open the preview window after entering the Markdown buffer
" default: 0
let g:mkdp_auto_start = 0

" set to 1, the nvim will auto close current preview window when changing from Markdown buffer to another buffer
" default: 1
let g:mkdp_auto_close = 1

" normal/insert mappings
"nmap <C-s> <Plug>MarkdownPreview
"nmap <M-s> <Plug>MarkdownPreviewStop
nmap <C-p> <Plug>MarkdownPreviewToggle

" browser
function OpenMarkdownPreview (url)
    execute "silent ! open -a 'Google Chrome' -n --args --new-tab " . a:url
    redraw!
endfunction
let g:mkdp_browserfunc = 'OpenMarkdownPreview'

"====[ preservim/vim-markdown ]====
let g:vim_markdown_folding_disabled = 1

"====[ preservim/vim-markdown ]====
" https://github.com/junegunn/fzf/blob/master/README-VIM.md#configuration

"====[ google/vim-maktaba ]====
" Add helloworld to the runtime path. (Normally this would be done with another
" Plugin command, but helloworld doesn't have a repository of its own.)
call maktaba#plugin#Install(maktaba#path#Join([maktaba#Maktaba().location, 'examples', 'helloworld']))

"====[ google/vim-glaive ]====
let vimrc_dir = $MYVIMRC->resolve()->fnamemodify(':h') . "/"
let google_java_fmt_jar_path = vimrc_dir . "google-java-format-latest.jar"
let java_fmt_cmd = "java -jar " . google_java_fmt_jar_path

call glaive#Install()
" Optional: Enable codefmt's default mappings on the <Leader>= prefix.
Glaive codefmt plugin[mappings]
Glaive codefmt google_java_executable=`g:java_fmt_cmd`

"====[ google/vim-codefmt ]====
augroup autoformat_settings
  autocmd FileType bzl AutoFormatBuffer buildifier
  autocmd FileType c,cpp,proto,javascript,typescript,arduino AutoFormatBuffer clang-format
  autocmd FileType clojure AutoFormatBuffer cljstyle
  autocmd FileType dart AutoFormatBuffer dartfmt
  autocmd FileType elixir,eelixir,heex AutoFormatBuffer mixformat
  autocmd FileType fish AutoFormatBuffer fish_indent
  autocmd FileType gn AutoFormatBuffer gn
  autocmd FileType go AutoFormatBuffer gofmt
  autocmd FileType haskell AutoFormatBuffer ormolu
  " Alternative for web languages: prettier
  autocmd FileType html,css,sass,scss,less,json AutoFormatBuffer js-beautify
  autocmd FileType java AutoFormatBuffer google-java-format
  autocmd FileType jsonnet AutoFormatBuffer jsonnetfmt
  autocmd FileType julia AutoFormatBuffer JuliaFormatter
  autocmd FileType kotlin AutoFormatBuffer ktfmt
  autocmd FileType lua AutoFormatBuffer luaformatterfiveone
  autocmd FileType markdown AutoFormatBuffer prettier
  autocmd FileType ocaml AutoFormatBuffer ocamlformat
  autocmd FileType python AutoFormatBuffer black
  " Alternative: autocmd FileType python AutoFormatBuffer autopep8
  autocmd FileType ruby AutoFormatBuffer rubocop
  autocmd FileType rust AutoFormatBuffer rustfmt
  autocmd FileType swift AutoFormatBuffer swift-format
  autocmd FileType vue AutoFormatBuffer prettier
augroup END


"====[ FileType Specifics ]====
autocmd Filetype bash,shell,sh setlocal expandtab tabstop=2 sts=2 shiftwidth=2
autocmd Filetype java          setlocal expandtab tabstop=2 sts=2 shiftwidth=2
autocmd Filetype markdown      setlocal expandtab tabstop=2 sts=2 shiftwidth=2
autocmd Filetype py,python     setlocal expandtab tabstop=4 sts=4 shiftwidth=4
autocmd Filetype go,gomod      setlocal listchars=tab:\ \ ,trail:·,nbsp:~"
autocmd Filetype c,cpp         setlocal expandtab tabstop=4 sts=4 shiftwidth=4 listchars=tab:\ \ ,trail:·,nbsp:~"
autocmd Filetype gitconfig     setlocal expandtab tabstop=4 sts=4 shiftwidth=4
set rtp^="/Users/qimer/.opam/default/share/ocp-indent/vim"
